In [104]:
#indexing
import numpy as np
array=np.array([2,4,6,8,10,12,14,16])
third_element=array[2]
print(third_element)

6


In [105]:
#slicing
import numpy as np
slice_1d=array[1:6]
print(slice_1d)

[ 4  6  8 10 12]


In [106]:
#Reshaping
import numpy as np
reshaped_array=array.reshape((4,2))
print(reshaped_array)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [107]:
#Joining
import numpy as np
arr1=np.array([1,3,5,7])
arr2=np.array([2,4,6,8])
concatenated_array=np.concatenate((arr1,arr2))
print(concatenated_array)

[1 3 5 7 2 4 6 8]


In [108]:
#Iterating
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [109]:
#spliting
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
split_array=np.array_split(arr,5)
print(split_array)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


In [110]:
#searching
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [111]:
#sorting
import numpy as np

arr = np.array([3, 2,23,56,6,8, 0, 1])

print(np.sort(arr))

[ 0  1  2  3  6  8 23 56]


In [112]:
#filtring
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


[41 43]
