In [165]:
#creating numpy array from python list
import numpy as np
list=[1,2,3,4,5,6]
numPy_array=np.array(list)
print(numPy_array)

[1 2 3 4 5 6]


In [166]:
#creating numpy array from python tuple
import numpy as np
tuple=(1,2,3,4,5,6)
numPy_array=np.array(tuple)
print(numPy_array)

[1 2 3 4 5 6]


In [167]:
#creating numpy array from nested python list
import numpy as np
nested_list=[[1,3,5,9],[2,4,6,8]]
numpy_array=np.array(nested_list)
print(numpy_array)

[[1 3 5 9]
 [2 4 6 8]]


In [168]:
#creating a numpy array usingnp.arange
import numpy as np
numpy_array=np.arange(0,20,5)
print(numpy_array)

[ 0  5 10 15]


In [169]:
#creating numpy array from zeros
import numpy as np
numpy_array=np.zeros((3,5))
print(numpy_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [170]:
#creating numpy array from ones
import numpy as np
numpy_array=np.ones(5)
print(numpy_array)

[1. 1. 1. 1. 1.]


In [171]:
#create an empty array
import numpy as np
numpy_array=np.empty(5)
print(numpy_array)

[1. 1. 1. 1. 1.]


In [172]:
#creating numpy array with diagonals element 1
import numpy as np
numpy_array=np.eye(3,5)
print(numpy_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [173]:
#creating numpy array from zeros
import numpy as np
numpy_array=np.zeros((3,5))
print(numpy_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [174]:
#creating numpy array with linspace
import numpy as np
numpy_array=np.linspace(1,20,5)
print(numpy_array)

[ 1.    5.75 10.5  15.25 20.  ]


In [175]:
#creating numpy array from random function,rand()[used to generate random value between 0 to 1]
import numpy as np
numpy_array=np.random.rand(5)
print(numpy_array)

[0.36449997 0.31003922 0.96139465 0.19919844 0.77515582]


In [176]:
#creating numpy array from random function,randn()[used to generate random value closed to 0 may be +ve or -ve]
import numpy as np
numpy_array=np.random.randn(5)
print(numpy_array)

[-1.5251803  -0.16336144 -0.943708    0.30183086 -1.80067534]


In [177]:
#creating numpy array from random function,ranf()[used to generate random floats value between [0 to 1)]
import numpy as np
numpy_array=np.random.ranf(5)
print(numpy_array)

[0.5893246  0.04180185 0.86564118 0.33017709 0.27573028]


In [178]:
#creating numpy array from random function,randint()[used to generate random number between a given value ]
import numpy as np
numpy_array=np.random.randint(1,20,5)
print(numpy_array)

[16 17 13 17 19]
