In [65]:
#element wise addition
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
addition=np.add(arr1,arr2)
print(addition)

[ 3  7 11 15 19]


In [66]:
#element wise multiplication
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
multiplication=np.multiply(arr1,arr2)
print(multiplication)

[ 2 12 30 56 90]


In [67]:
#element wise sin
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
sine_value=np.sin(arr1)
print(sine_value)

[ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]


In [68]:
#sum of all elements
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
sumation=np.sum(arr2)
print(sumation)

30


In [69]:
#sum of all elements
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
mean_value=np.mean(arr2)
print(mean_value)

6.0


In [70]:
#standard deviation
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
standard_deviation=np.std(arr2)
print(standard_deviation)

2.8284271247461903


In [71]:
#transpose
import numpy as np
arr1=np.array([1,3,5,7,9,11,13,15,17])
arr2=np.array([2,4,6,8,10,12])
A=np.array(arr1).reshape(3,3)
print(A)
print(A.transpose())

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
