In [124]:
#element wise addition
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
addition=np.add(arr1,arr2)
print(addition)

[ 3  7 11 15 19]


In [125]:
#element wise multiplication
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
multiplication=np.multiply(arr1,arr2)
print(multiplication)

[ 2 12 30 56 90]


In [126]:
#element wise addition
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
m=arr1+arr2
print(m)

[ 3  7 11 15 19]


In [127]:
#subtraction
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
m=arr1-arr2
print(m)

[-1 -1 -1 -1 -1]


In [128]:
#Multiplication
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
m=arr1*arr2
print(m)

[ 2 12 30 56 90]


In [129]:
#division
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
m=arr1/arr2
print(m)

[0.5        0.75       0.83333333 0.875      0.9       ]


In [130]:
#Exponentiation
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
m=arr1**arr2
print(m)

[         1         81      15625    5764801 -808182895]


In [131]:
#Modulo
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
m=arr1%arr2
print(m)

[1 3 5 7 9]


In [132]:
#element wise addition
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
m=arr1+arr2
print(m)

[ 3  7 11 15 19]


In [133]:
#element wise sin
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
sine_value=np.sin(arr1)
print(sine_value)

[ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]


In [134]:
#sum of all elements
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
sumation=np.sum(arr2)
print(sumation)

30


In [135]:
#mean of all elements
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
mean_value=np.mean(arr2)
print(mean_value)

6.0


In [136]:
#standard deviation
import numpy as np
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
standard_deviation=np.std(arr2)
print(standard_deviation)

2.8284271247461903


In [137]:
#transpose
import numpy as np
arr1=np.array([1,3,5,7,9,11,13,15,17])
arr2=np.array([2,4,6,8])
A=np.array(arr1).reshape(3,3)
B=np.array(arr2).reshape(2,2)
print(A)
print("          ")
print(A.transpose())
print("          ")
print(B)
print("           ")
print(B.transpose())


[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
          
[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
          
[[2 4]
 [6 8]]
           
[[2 6]
 [4 8]]
